{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoverfly.auth.secretName" . }}
  labels:
    {{- include "hoverfly.labels" . | nindent 4 }}
  {{- with (include "hoverfly.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | b64enc | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
