{{- if .Values.serviceAccount.create -}}
{{- $annotations := merge (deepCopy .Values.serviceAccount.annotations) (deepCopy .Values.commonAnnotations) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hoverfly.serviceAccountName" . }}
  labels:
    {{- include "hoverfly.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- include "hoverfly.tplvalues" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
